### PR TITLE
export additional *_FULL_PATH constants

### PR DESCRIPTION
**Pull request by ZeusJunior**
I found when working with this that creating my own URLs was quite cumbersome. Couple different variables and options to take into account and I made the mistake of adding unnecessary `/`'s
```js
const url = `http://bot:3000${FRIENDS_BASE_URL}${FRIEND_MESSAGE_PATH}`.replace(...)`
```
So in bot-data and bot-manager I've added exports for *_FULL_PATH's, to make it a little more clear when to use which url
```js
const url = `http://bot:3000${FRIEND_MESSAGE_FULL_PATH}`.replace(...)`
```
I left bptf-manager alone as it wasn't fully using the same system (listings for example doesn't export any paths) 

I would probably prefer to not export the other partial path variables at all but keep them internal for the controllers only, should you want to, to limit the number of results in autocomplete. However that would be a breaking change so I'd like to hear your thoughts on that

### CODE REVIEW

**Comment by Nicklason** [comment]
I would be fine with making the paths private and only exposing the full paths. But then a new library needs to be made which contains the private paths. The library could be called “bot-data-internal”.

**Review by Nicklason — DISMISSED** [review]
I think making a function like fullPath(path) would be nicer instead of using string templating for everything. The function could even be reused in the different files if it took the full path as an argument too.

**Comment by ZeusJunior** [comment]
> I would be fine with making the paths private and only exposing the full paths. But then a new library needs to be made which contains the private paths. The library could be called “bot-data-internal”.

Why would that be required?
The cases where the manager uses bot-data to make requests to the bot (escrow, bot info, inventories and trades) could easily be replaced with the new full paths
Same goes for bot using bot-manager-data, which is only heartbeats

**Comment by Nicklason** [comment]
The controllers use the paths. If you want to remove all the extra paths from the autocomplete on the bot-data and bit-manager-data libraries then they need to be moved into a private library.

**Pull request merged**
